### ISSUE TITLE
Running on scipy 1.8.1 ok but not scipy 1.9

### ISSUE THREAD

**Issue by cylammarco** [cylammarco/WDPhotTools#18]
Hi, thanks for letting me know. Also found that when running on scipy 1.8.1 everything runs ok but when running on scipy 1.9 I get the following error: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''.
![Screenshot 2022-08-04 at 16 13 44](https://user-images.githubusercontent.com/108353761/182883204-97a21fe7-3306-4a0d-ac1d-af88629c178d.png)

_Originally posted by @cm775 in https://github.com/cylammarco/WDPhotTools/discussions/15#discussioncomment-3326255_

**Comment by cm775** [comment]
Using numpy 1.23.0, wdphottools v0.0.3

**Comment by cylammarco** [comment]
Fixed together with #17

**Comment by cylammarco** [comment]
With the fix, I can't guarantee it works with scipy 1.8... please let me know if someone needs to use older versions of scipy and it does not work for you now.
